CREATE TABLE MT_USER (
    ID            SERIAL       PRIMARY KEY,
    USERNAME      VARCHAR(64)  NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE          VARCHAR(32)  NOT NULL,
    CREATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT    TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT UQ_MT_USER_USERNAME UNIQUE (USERNAME),
    CONSTRAINT CK_MT_USER_ROLE CHECK (ROLE IN ('USER', 'ADMIN'))
);

CREATE TABLE TT_QUESTION (
    ID             SERIAL       PRIMARY KEY,
    TITLE          VARCHAR(100) NOT NULL,
    BODY           TEXT         NOT NULL,
    STATUS         VARCHAR(16)  NOT NULL,
    CREATED_BY     BIGINT       NOT NULL,
    BEST_ANSWER_ID BIGINT       NULL,
    CREATED_AT     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT     TIMESTAMP    NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TT_QUESTION_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES MT_USER(ID),
    CONSTRAINT CK_TT_QUESTION_STATUS
    CHECK (STATUS IN ('UNANSWERED', 'ANSWERED', 'CLOSED'))
);

CREATE TABLE TT_ANSWER (
    ID          SERIAL    PRIMARY KEY,
    QUESTION_ID BIGINT    NOT NULL,
    BODY        TEXT      NOT NULL,
    CREATED_BY  BIGINT    NOT NULL,
    CREATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT  TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT FK_TT_ANSWER_QUESTION_ID
    FOREIGN KEY (QUESTION_ID) REFERENCES TT_QUESTION(ID),
    CONSTRAINT FK_TT_ANSWER_CREATED_BY
    FOREIGN KEY (CREATED_BY) REFERENCES MT_USER(ID)
);

-- BEST_ANSWER_ID FK
ALTER TABLE TT_QUESTION
    ADD CONSTRAINT FK_TT_QUESTION_BEST_ANSWER_ID
        FOREIGN KEY (BEST_ANSWER_ID) REFERENCES TT_ANSWER(ID);

-- Indexes
CREATE INDEX IF NOT EXISTS IDX_TT_ANSWER_QUESTION_ID
    ON TT_ANSWER (QUESTION_ID);

CREATE INDEX IF NOT EXISTS IDX_TT_QUESTION_STATUS
    ON TT_QUESTION (STATUS);

CREATE INDEX IF NOT EXISTS IDX_TT_QUESTION_CREATED_AT
    ON TT_QUESTION (CREATED_AT);

-- Add Admin and User
INSERT INTO MT_USER (USERNAME, PASSWORD_HASH, ROLE)
VALUES ('admin', '$2a$10$uSt897N1ir1bx7fNmQ8yT.yHAASvXjZzq6oVSNQHQlQubLFqFA2DC', 'ADMIN'),
       ('user', '$2a$10$uSt897N1ir1bx7fNmQ8yT.yHAASvXjZzq6oVSNQHQlQubLFqFA2DC', 'USER');